version: '2'
services:
    robblog-app:
        image: robblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://robblog-mysql:3306/robblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    robblog-mysql:
        extends:
            file: mysql.yml
            service: robblog-mysql
